// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZcIvAVScwv728osne9FG8Hj2DVJFdHS8',
    appId: '1:703649607267:web:8c9fcb54399425146b1256',
    messagingSenderId: '703649607267',
    projectId: 'syg-materiales',
    authDomain: 'syg-materiales.firebaseapp.com',
    storageBucket: 'syg-materiales.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhupb8dgJ4k_h9HOXOisy6nALuC7Hz37I',
    appId: '1:703649607267:android:c0c969e9388e74fe6b1256',
    messagingSenderId: '703649607267',
    projectId: 'syg-materiales',
    storageBucket: 'syg-materiales.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Ku4E0M5NGeGYIjrHeRZUpqSC2IUImc4',
    appId: '1:703649607267:ios:63350fc337bdf2b26b1256',
    messagingSenderId: '703649607267',
    projectId: 'syg-materiales',
    storageBucket: 'syg-materiales.firebasestorage.app',
    iosBundleId: 'com.syg.sygMaterialesFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZcIvAVScwv728osne9FG8Hj2DVJFdHS8',
    appId: '1:703649607267:web:2550a5681280cf196b1256',
    messagingSenderId: '703649607267',
    projectId: 'syg-materiales',
    authDomain: 'syg-materiales.firebaseapp.com',
    storageBucket: 'syg-materiales.firebasestorage.app',
  );
}
